[Feat] Added Payment Gateway Stripe
bsoc-bitbyte/GetIt pull request #106
Opened 2023-12-10 17:52 UTC by Priyansh61

## Overview

1. This PR adds payment gateway for the REST API
2. This PR does the following: We will be using the Stripe payment gateway to make payments within our application and the gateway has been added.

We have also created a webhook to check the status of the payment iniitiated by the user and on that basis only we will be updating the  status of the ticket.

This still needs to be tested with the TESTING CREDENTIALS.

## Essential Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [ ] The PR is made from a branch that's **not** called "main/master".

## Proof that changes are correct

## PR Pointers

- If you need a review or an answer to a question, and don't have permissions to assign people, **leave a comment** like the following: "{{Question/comment}} @{{reviewer_username}} PTAL".
- Never force push. If you do, your PR will be closed.

2023-12-12 09:07 UTC, arminpatel requested changes
also could you add a default choice for `status` in `ticket` model?

2023-12-28 13:15 UTC, ChaudharyRaman approved these changes

2023-12-28 13:15 UTC, arminpatel approved these changes

2023-12-28 13:15 UTC, merged

2024-01-25 19:11 UTC, aryan1113 reviewed
Add a super().save function ni backend/tickets/models.py, to have a full clean
something along the lines of 

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)