product page
bsoc-bitbyte/GetIt pull request #13
Opened 2023-06-11 07:15 UTC by rrtk857

## Overview

1. This PR fixes or fixes part of #9 
2. This PR does the following: This PR contain product page design with the use of API, HTML, CSS, JavaScript. the Product page has information about product and images, and buttons to buy it or add to cart. 
![Screenshot (36)](https://github.com/bsoc-bitbyte/GetIt/assets/129523259/fa237601-6d0b-49fe-b16b-eb791e291757)
![Screenshot (37)](https://github.com/bsoc-bitbyte/GetIt/assets/129523259/fb0a6d2e-f888-4d1d-8036-6e920783bacd)
 

## Essential Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [ ] The PR is made from a branch that's **not** called "main/master".

## Proof that changes are correct

## PR Pointers

- If you need a review or an answer to a question, and don't have permissions to assign people, **leave a comment** like the following: "{{Question/comment}} @{{reviewer_username}} PTAL".
- Never force push. If you do, your PR will be closed.

2023-06-11 10:54 UTC, arminpatel commented
@rrtk857 in case you wouldn't be updating your PR to use tailwind css, create a issue to fix this

2023-06-11 11:15 UTC, rrtk857 commented
@arminpatel, I will try to update it.

2023-06-11 11:41 UTC, arminpatel reviewed
@rrtk857  , great job so far. Just wanted to share a couple of suggestions with you:

- When you're contributing to a project, it's always helpful to go through the [CONTRIBUTING.md](https://github.com/bsoc-bitbyte/GetIt/blob/main/CONTRIBUTING.md#standard-commit-message-) file. It contains some conventions and guidelines to follow. It's a good idea to familiarize yourself with those before you start contributing.

- I noticed that your commit message style doesn't quite match what's mentioned in the CONTRIBUTING.md file for this project. No worries, though! It's completely fine for your first time contributing. Just remember to keep this in mind for your future contributions.

- Also, don't forget to update the PR title to match the recommended format, similar to the commit messages. Consistency in both commit messages and PR titles helps keep things organized and clear within the project.

2023-06-11 12:12 UTC, thejaysharma commented on pages/products/_id.vue
> +        <div i="image_row">
hey @rrtk857, You can implement arrows function to show more product images Or you can make issue for the same. For reference :- https://www.youtube.com/watch?v=Y36QpYcnbQY&ab_channel=DennisIvy

2023-06-11 12:17 UTC, thejaysharma commented on pages/products/_id.vue
> +            <div id="circles">
the colour that the user is presently viewing should be active.

2023-06-11 12:21 UTC, thejaysharma requested changes
Hey @rrtk857, good job! Here are a few minor adjustments you may make.

2023-06-11 19:37 UTC, Priyansh61 commented
@JawHawk @tushitshukla03 PTAL!

2023-06-11 19:38 UTC, Priyansh61 commented
Hey @rrtk857 Please address the above comments. If you need any help do let us know :)

2023-06-12 04:19 UTC, rrtk857 commented
@arminpatel @thejaysharma @Priyansh61, Thanks for all the suggestions, I'll update my PR accordingly.
I have few doubts regarding tailwind CSS, I have installed it according to the given instructions, but I am bit confused in Step 2,3.
I am unable to understand where I have to include these files, so I have included it in the page folder only and it is working also.
So, I am attaching the screenshots below, please check it once that it is right, or I have to do any other changes.
![Screenshot (41)](https://github.com/bsoc-bitbyte/GetIt/assets/129523259/cd22bf75-a80f-4d8a-ab16-1f40bc85d92b)
![Screenshot (42)](https://github.com/bsoc-bitbyte/GetIt/assets/129523259/604bdb1b-7705-4b80-8807-c6c27ea77c9b)
![Screenshot (43)](https://github.com/bsoc-bitbyte/GetIt/assets/129523259/125edda1-db10-4841-b7f8-b76d32670ffc)
![Screenshot (44)](https://github.com/bsoc-bitbyte/GetIt/assets/129523259/7993eae3-b546-44df-89c6-eb57f9c6ef1e)
![Screenshot (45)](https://github.com/bsoc-bitbyte/GetIt/assets/129523259/ca82d798-b75e-4cfe-95b5-78da72c3bdc3)

2023-06-12 05:32 UTC, thejaysharma commented
@rrtk857 Tailwindcss has already been set up for your convenience. All you have to do is include it into your code.

2023-06-13 17:45 UTC, rrtk857 commented
I have made the changes and also used tailwind CSS.

https://github.com/bsoc-bitbyte/GetIt/assets/129523259/a6333827-2b9b-4d2b-88a1-fd5943f38115

2023-06-13 17:52 UTC, thejaysharma commented
Push your changes so that we can review and merge it.

2023-06-14 04:23 UTC, rrtk857 commented
I have made some more changes. Please review it.

2023-06-14 18:15 UTC, prernadabi23 approved these changes

2023-06-15 06:05 UTC, rrtk857 commented
I have made all the required changes. Please review it.

https://github.com/bsoc-bitbyte/GetIt/assets/129523259/f4c9e02c-bb08-4257-8a98-ee3332f20690

2023-06-16 11:31 UTC, Priyansh61 approved these changes
LGTM :+1:

2023-06-16 11:32 UTC, merged

2023-07-15 05:06 UTC, rrtk857 commented
@Priyansh61, Difficulty of PR?

2023-07-15 08:21 UTC, Priyansh61 commented
@thejaysharma @prernadabi23 @tushitshukla03 label this PR plss?